version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
    labels:
      - "yarn"
      - "dependencies"
    reviewers:
      - "Nexushunter"
      - "Clairev3"