version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"
    groups:
      aws:
        patterns:
          - "aws*"
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go-v2"
        update-types: ["version-update:semver-patch"]
    labels:
      - "go"
      - "dependencies"
    reviewers:
      - "danharasymiw"
      - "grevian"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
