version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
    labels:
      - "yarn"
      - "dependencies"
    reviewers:
      - "Nexushunter"
      - "Clairev3"
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"
    labels:
      - "go"
      - "dependencies"
    reviewers:
      - "DanHarasymiw"
      - "grevian"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"