services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "salt"
      MYSQL_ROOT_USER: "root"
      MYSQL_PASSWORD: "salt"
      MYSQL_ROOT_PASSWORD: "salt"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./internal/store/rdb/migrations/0000-init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psalt"]
      interval: 2s
      retries: 20
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    image: salttoday2-app:latest
    command: ["/app/service-bin"]
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - MYSQL_URL=root:salt@tcp(mysql:3306)/salt
      - RAILWAY_PUBLIC_DOMAIN=localhost  # Makes server bind to 0.0.0.0 instead of localhost
    depends_on:
      mysql:
        condition: service_healthy
  
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
      platforms:
        - linux/amd64
    platform: linux/amd64
    image: salttoday2-scraper:latest
    command: ["/scraper-bin", "7"]
    environment:
      - MYSQL_URL=root:salt@tcp(mysql:3306)/salt
    depends_on:
      mysql:
        condition: service_healthy
