providers = ['go']

[phases.setup]
nixPkgs = [
  "...", 
  "tailwindcss",
  "chromium",
]

[phases.go-templ]
cmds = [
  'go install github.com/a-h/templ/cmd/templ@latest',
  '/root/go/bin/templ generate',
]
[phases.build]
cmds = [
  'go build -o service-bin cmd/server/main.go',
  'go build -o scraper-bin cmd/scraper/main.go',
]

[phases.tailwind]
cmds = [
	'tailwindcss -c ./tailwind.config.js -i ./public/styles.css -o ./public/output.css',
]

[phases.playwright]
cmds = [
  'go install github.com/playwright-community/playwright-go/cmd/playwright@latest',
  '/root/go/bin/playwright install chromium',
  '/root/go/bin/playwright install-deps chromium'
]

[start]
cmd = './service-bin'
