name: UI CI
on: 
  pull_request:
  workflow_dispatch:

# Provide the default working directory for all run commands
defaults:
  run:
    working-directory: ui

jobs:
  ts-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock
      - name: Install
        run: yarn
      - name: Test
        run: yarn test